version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    command: poetry run 
    environment:
      STORE_DEBUG: debug
      STORE_USERNAME: username
      STORE_PASSWORD: password
      STORE_SERVE_PORT: 8020
    ports:
      - "8020:8020"

